<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Uncap the House! The Case for Increased Representation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="representation_files/libs/clipboard/clipboard.min.js"></script>
<script src="representation_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="representation_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="representation_files/libs/quarto-html/popper.min.js"></script>
<script src="representation_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="representation_files/libs/quarto-html/anchor.min.js"></script>
<link href="representation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="representation_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="representation_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="representation_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="representation_files/libs/bootstrap/bootstrap-67270d1595a62d14f123c043d4fb2f18.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Uncap the House! The Case for Increased Representation</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidytuesdayR"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidytuesdayR)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>tuesdata <span class="ot">&lt;-</span> tidytuesdayR<span class="sc">::</span><span class="fu">tt_load</span>(<span class="st">'2024-11-05'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dem_df<span class="ot">&lt;-</span> tuesdata<span class="sc">$</span>democracy_data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(httr)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyjson)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jsonlite)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glue)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>base_url <span class="ot">&lt;-</span> <span class="st">"https://api.api-ninjas.com/v1/population"</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>api <span class="ot">&lt;-</span> <span class="fu">Sys.getenv</span>(<span class="st">"API_NINJAS_KEY"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>get_pop_data <span class="ot">&lt;-</span> <span class="cf">function</span>(country) {</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  country_url <span class="ot">&lt;-</span> <span class="fu">glue</span>(<span class="st">"{base_url}?country={URLencode(country, reserved = TRUE)}"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  countries <span class="ot">&lt;-</span> <span class="fu">GET</span>(country_url, <span class="fu">add_headers</span>(<span class="st">"X-Api-Key"</span> <span class="ot">=</span> api))</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">status_code</span>(countries) <span class="sc">!=</span> <span class="dv">200</span>) {</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">message</span>(<span class="st">"Failed for "</span>, country, <span class="st">": status "</span>, <span class="fu">status_code</span>(countries))</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">message</span>(<span class="fu">content</span>(countries, <span class="st">"text"</span>, <span class="at">encoding =</span> <span class="st">"UTF-8"</span>))</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="cn">NULL</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  tx <span class="ot">&lt;-</span> <span class="fu">content</span>(countries, <span class="st">"text"</span>, <span class="at">encoding =</span> <span class="st">"UTF-8"</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (tx <span class="sc">==</span> <span class="st">""</span>) {</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">message</span>(<span class="st">"Empty response for "</span>, country)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="cn">NULL</span>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  countries_data <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(tx)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(countries_data<span class="sc">$</span>historical_population)) {</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">message</span>(<span class="st">"No historical population for "</span>, country)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="cn">NULL</span>)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>  countries_data<span class="sc">$</span>historical_population <span class="sc">%&gt;%</span></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">country =</span> country)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>pop_data <span class="ot">&lt;-</span> <span class="fu">map</span>(<span class="fu">unique</span>(dem_df<span class="sc">$</span>country_name), <span class="at">.f =</span> get_pop_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Afghanistan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Albania: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Algeria: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Angola: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Anguilla: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Antigua and Barbuda: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Argentina: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Armenia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Aruba: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Australia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Austria: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Azerbaijan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Bahamas: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Bahrain: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Bangladesh: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Barbados: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Belarus: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Belgium: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Belize: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Benin: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Bermuda: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Bhutan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Bolivia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Bosnia and Herzegovina: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Botswana: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Brazil: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for British Virgin Islands: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Brunei: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Bulgaria: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Burkina Faso: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Burundi: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Cambodia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Cameroon: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Canada: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Cape Verde: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Cayman Islands: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Central African Republic: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Chad: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Chile: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for China: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Colombia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Comoros: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Congo, Dem. Rep.: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Congo, Republic of: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Cook Islands: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Costa Rica: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Côte d`Ivoire: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Croatia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Cuba: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Curacao: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Cyprus: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Czech Republic: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Denmark: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Djibouti: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Dominica: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Dominican Republic: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Ecuador: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Egypt: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for El Salvador: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Equatorial Guinea: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Eritrea: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Estonia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Ethiopia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Fiji: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Finland: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for France: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Gabon: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Gambia, The: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Georgia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Germany: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Ghana: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Gibraltar: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Greece: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Grenada: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Guam: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Guatemala: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Guinea: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Guinea-Bissau: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Guyana: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Haiti: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Honduras: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Hong Kong: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Hungary: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Iceland: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for India: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Indonesia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Iran: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Iraq: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Ireland: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Israel: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Italy: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Jamaica: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Japan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Jordan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Kazakhstan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Kenya: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Kiribati: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Korea, People's Republic: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Korea, Republic of: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Kuwait: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Kyrgyzstan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Laos: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Latvia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Lebanon: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Lesotho: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Liberia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Libya: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Liechtenstein: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Lithuania: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Luxembourg: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Macao: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Madagascar: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Malawi: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Malaysia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Maldives: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Mali: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Malta: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Marshall Islands: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Mauritania: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Mauritius: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Mexico: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Micronesia, Fed. Sts.: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Moldova: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Monaco: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Mongolia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Montenegro: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Morocco: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Mozambique: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Myanmar: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Namibia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Nauru: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Nepal: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Netherlands: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for New Zealand: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Nicaragua: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Niger: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Nigeria: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Northern Mariana Islands: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for North Macedonia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Norway: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Oman: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Pakistan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Palau: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Panama: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Papua New Guinea: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Paraguay: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Peru: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Philippines: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Poland: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Portugal: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Puerto Rico: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Qatar: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Romania: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Russia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Rwanda: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Samoa: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Sao Tome and Principe: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Saudi Arabia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Senegal: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Serbia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Seychelles: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Sierra Leone: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Singapore: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Sint Maarten: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Slovak Republic: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Slovenia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Solomon Islands: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Somalia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for South Africa: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for South Sudan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Spain: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Sri Lanka: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for St. Kitts &amp; Nevis: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for St. Lucia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for St.Vincent &amp; Grenadines: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Sudan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Suriname: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Swaziland: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Sweden: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Switzerland: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Syria: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Taiwan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Tajikistan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Tanzania: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Thailand: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Timor-Leste: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Togo: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Tonga: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Trinidad &amp;Tobago: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Tunisia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Turkey: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Turkmenistan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Turks and Caicos: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Tuvalu: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Uganda: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Ukraine: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for United Arab Emirates: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for United Kingdom: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for United States: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Uruguay: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for US Virgin Islands: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Uzbekistan: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Vanuatu: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Venezuela: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Vietnam: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Yemen: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Zambia: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Failed for Zimbabwe: status 400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>{"error": "Monthly quota exceeded. Consider upgrading your subscription or wait until the API renew date."}</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb424"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb424-1"><a href="#cb424-1" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(pop_data,<span class="st">"pop_data.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb425"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb425-1"><a href="#cb425-1" aria-hidden="true" tabindex="-1"></a>pop_data <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"pop_data (1).rds"</span>)</span>
<span id="cb425-2"><a href="#cb425-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb425-3"><a href="#cb425-3" aria-hidden="true" tabindex="-1"></a>clean_df <span class="ot">&lt;-</span> pop_data <span class="sc">%&gt;%</span></span>
<span id="cb425-4"><a href="#cb425-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">keep</span>(<span class="sc">~</span> <span class="fu">is.data.frame</span>(.x) <span class="sc">&amp;&amp;</span> <span class="fu">nrow</span>(.x) <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb425-5"><a href="#cb425-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(<span class="sc">~</span> .x <span class="sc">%&gt;%</span> <span class="fu">select</span>(country, year, population)) <span class="sc">%&gt;%</span></span>
<span id="cb425-6"><a href="#cb425-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb426"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb426-1"><a href="#cb426-1" aria-hidden="true" tabindex="-1"></a>dem2_df <span class="ot">&lt;-</span> dem_df <span class="sc">%&gt;%</span></span>
<span id="cb426-2"><a href="#cb426-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">&gt;=</span><span class="dv">1955</span> <span class="sc">&amp;</span> year<span class="sc">%%</span><span class="dv">5</span><span class="sc">==</span><span class="dv">0</span>)<span class="sc">%&gt;%</span></span>
<span id="cb426-3"><a href="#cb426-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">country =</span> <span class="st">"country_name"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb427"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb427-1"><a href="#cb427-1" aria-hidden="true" tabindex="-1"></a>clean2_df <span class="ot">&lt;-</span> clean_df <span class="sc">%&gt;%</span></span>
<span id="cb427-2"><a href="#cb427-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">%%</span><span class="dv">5</span><span class="sc">==</span><span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb427-3"><a href="#cb427-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(country, year)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb428"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb428-1"><a href="#cb428-1" aria-hidden="true" tabindex="-1"></a>final_df <span class="ot">&lt;-</span> <span class="fu">left_join</span>(dem2_df, clean2_df, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"country"</span>, <span class="st">"year"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb429"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb429-1"><a href="#cb429-1" aria-hidden="true" tabindex="-1"></a>final_df <span class="ot">&lt;-</span> final_df <span class="sc">%&gt;%</span></span>
<span id="cb429-2"><a href="#cb429-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(is_democracy<span class="sc">==</span><span class="cn">TRUE</span>)<span class="sc">%&gt;%</span></span>
<span id="cb429-3"><a href="#cb429-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pop_prop =</span> population<span class="sc">/</span><span class="fu">rowSums</span>(<span class="fu">cbind</span>(upper_house_members,lower_house_members, third_house_members), <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="cb429-4"><a href="#cb429-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb429-5"><a href="#cb429-5" aria-hidden="true" tabindex="-1"></a><span class="co"># head(final_df[c("country", "year", "population","pop_prop")])</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb430"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb430-1"><a href="#cb430-1" aria-hidden="true" tabindex="-1"></a>happiness <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"datasets/whr_data.csv"</span>)</span>
<span id="cb430-2"><a href="#cb430-2" aria-hidden="true" tabindex="-1"></a><span class="co"># I'm not sure why there are empty columns beyond those we are using, the file very clearly only had 13 columns. I don't think this should be an issue, but we're not gonna be using that whole dataset anyway.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb431"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb431-1"><a href="#cb431-1" aria-hidden="true" tabindex="-1"></a>happiness_clean <span class="ot">&lt;-</span> happiness <span class="sc">%&gt;%</span></span>
<span id="cb431-2"><a href="#cb431-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb431-3"><a href="#cb431-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">country_name =</span> <span class="st">`</span><span class="at">Country name</span><span class="st">`</span>,</span>
<span id="cb431-4"><a href="#cb431-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> Year,</span>
<span id="cb431-5"><a href="#cb431-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">well_being =</span> <span class="st">`</span><span class="at">Life evaluation (3-year average)</span><span class="st">`</span>)</span>
<span id="cb431-6"><a href="#cb431-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-7"><a href="#cb431-7" aria-hidden="true" tabindex="-1"></a><span class="co">#find the years that both this data set and the dem_df covers, and then we'll filter the sets to match those years</span></span>
<span id="cb431-8"><a href="#cb431-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-9"><a href="#cb431-9" aria-hidden="true" tabindex="-1"></a><span class="co"># range(happiness_clean$year, na.rm = TRUE) # since 2011</span></span>
<span id="cb431-10"><a href="#cb431-10" aria-hidden="true" tabindex="-1"></a><span class="co"># range(dem_df$year, na.rm = TRUE) # 1950 to 2020</span></span>
<span id="cb431-11"><a href="#cb431-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-12"><a href="#cb431-12" aria-hidden="true" tabindex="-1"></a>dem_overlap <span class="ot">&lt;-</span> dem_df <span class="sc">%&gt;%</span></span>
<span id="cb431-13"><a href="#cb431-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&gt;=</span> <span class="dv">2011</span>)</span>
<span id="cb431-14"><a href="#cb431-14" aria-hidden="true" tabindex="-1"></a>happiness_overlap <span class="ot">&lt;-</span> happiness_clean <span class="sc">%&gt;%</span></span>
<span id="cb431-15"><a href="#cb431-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&lt;=</span> <span class="dv">2020</span>)</span>
<span id="cb431-16"><a href="#cb431-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-17"><a href="#cb431-17" aria-hidden="true" tabindex="-1"></a><span class="co"># now we merge them into one data frame</span></span>
<span id="cb431-18"><a href="#cb431-18" aria-hidden="true" tabindex="-1"></a><span class="co">#hdiXdem_df &lt;- dem_overlap %&gt;%</span></span>
<span id="cb431-19"><a href="#cb431-19" aria-hidden="true" tabindex="-1"></a>  <span class="co">#left_join(happiness_overlap, by = c("country_name", "year"))</span></span>
<span id="cb431-20"><a href="#cb431-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-21"><a href="#cb431-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-22"><a href="#cb431-22" aria-hidden="true" tabindex="-1"></a><span class="co"># this will weed out the countries that we weren't able to directly match by name</span></span>
<span id="cb431-23"><a href="#cb431-23" aria-hidden="true" tabindex="-1"></a><span class="co"># hdiXdem_df %&gt;%</span></span>
<span id="cb431-24"><a href="#cb431-24" aria-hidden="true" tabindex="-1"></a><span class="co"># filter(is.na(well_being)) %&gt;%</span></span>
<span id="cb431-25"><a href="#cb431-25" aria-hidden="true" tabindex="-1"></a><span class="co">#  distinct(country_name) %&gt;%</span></span>
<span id="cb431-26"><a href="#cb431-26" aria-hidden="true" tabindex="-1"></a><span class="co">#  arrange(country_name)</span></span>
<span id="cb431-27"><a href="#cb431-27" aria-hidden="true" tabindex="-1"></a><span class="co"># so that gave 208 countries which surprised me because the names looked the same to me. this makes me believe i messed up on the joining of the dataframes.</span></span>
<span id="cb431-28"><a href="#cb431-28" aria-hidden="true" tabindex="-1"></a><span class="co"># i'm gonna try the join again, only based off name, not year as well</span></span>
<span id="cb431-29"><a href="#cb431-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-30"><a href="#cb431-30" aria-hidden="true" tabindex="-1"></a><span class="co"># hdiXdem_df &lt;- dem_overlap %&gt;%</span></span>
<span id="cb431-31"><a href="#cb431-31" aria-hidden="true" tabindex="-1"></a> <span class="co"># left_join(happiness_overlap, by = "country_name")</span></span>
<span id="cb431-32"><a href="#cb431-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-33"><a href="#cb431-33" aria-hidden="true" tabindex="-1"></a><span class="co"># okay that isn't what we want either, that gives us a many to many dataframe, which is bad, so what I'll do is take the average of the happiness index and democracy index across the years and compare those. For reference, we don't want the many to many dataframe because it has 13010 rows.</span></span>
<span id="cb431-34"><a href="#cb431-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-35"><a href="#cb431-35" aria-hidden="true" tabindex="-1"></a><span class="co"># average of both data frames</span></span>
<span id="cb431-36"><a href="#cb431-36" aria-hidden="true" tabindex="-1"></a>avg_dem <span class="ot">&lt;-</span> dem_overlap <span class="sc">%&gt;%</span></span>
<span id="cb431-37"><a href="#cb431-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country_name) <span class="sc">%&gt;%</span></span>
<span id="cb431-38"><a href="#cb431-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_democracy =</span> <span class="fu">mean</span>(spatial_democracy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb431-39"><a href="#cb431-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-40"><a href="#cb431-40" aria-hidden="true" tabindex="-1"></a>avg_happiness <span class="ot">&lt;-</span> happiness_overlap <span class="sc">%&gt;%</span></span>
<span id="cb431-41"><a href="#cb431-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country_name) <span class="sc">%&gt;%</span></span>
<span id="cb431-42"><a href="#cb431-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_well_being =</span> <span class="fu">mean</span>(well_being, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb431-43"><a href="#cb431-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-44"><a href="#cb431-44" aria-hidden="true" tabindex="-1"></a><span class="co"># new dataframe</span></span>
<span id="cb431-45"><a href="#cb431-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-46"><a href="#cb431-46" aria-hidden="true" tabindex="-1"></a>hdiXdem_df <span class="ot">&lt;-</span> avg_dem <span class="sc">%&gt;%</span></span>
<span id="cb431-47"><a href="#cb431-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(avg_happiness, <span class="at">by =</span> <span class="st">"country_name"</span>)</span>
<span id="cb431-48"><a href="#cb431-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-49"><a href="#cb431-49" aria-hidden="true" tabindex="-1"></a><span class="co"># now check again for unmatched countries</span></span>
<span id="cb431-50"><a href="#cb431-50" aria-hidden="true" tabindex="-1"></a>hdiXdem_df <span class="sc">%&gt;%</span></span>
<span id="cb431-51"><a href="#cb431-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(avg_well_being)) <span class="sc">%&gt;%</span></span>
<span id="cb431-52"><a href="#cb431-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(country_name) <span class="sc">%&gt;%</span></span>
<span id="cb431-53"><a href="#cb431-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(country_name)</span>
<span id="cb431-54"><a href="#cb431-54" aria-hidden="true" tabindex="-1"></a><span class="co">#so that gives us 60 countries that are not in our happiness set that are in the democracy set. What we'll do now is use anti_join to see what countries are in the democracy set that are not in the happiness set, and vice versa.</span></span>
<span id="cb431-55"><a href="#cb431-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-56"><a href="#cb431-56" aria-hidden="true" tabindex="-1"></a>dem_not_happy <span class="ot">&lt;-</span> <span class="fu">anti_join</span>(avg_dem, avg_happiness, <span class="at">by =</span> <span class="st">"country_name"</span>)</span>
<span id="cb431-57"><a href="#cb431-57" aria-hidden="true" tabindex="-1"></a>happy_not_dem <span class="ot">&lt;-</span> <span class="fu">anti_join</span>(avg_happiness, avg_dem, <span class="at">by =</span> <span class="st">"country_name"</span>)</span>
<span id="cb431-58"><a href="#cb431-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-59"><a href="#cb431-59" aria-hidden="true" tabindex="-1"></a><span class="co"># nrow(dem_not_happy)</span></span>
<span id="cb431-60"><a href="#cb431-60" aria-hidden="true" tabindex="-1"></a><span class="co"># nrow(happy_not_dem)</span></span>
<span id="cb431-61"><a href="#cb431-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-62"><a href="#cb431-62" aria-hidden="true" tabindex="-1"></a><span class="co"># head(dem_not_happy, 20)</span></span>
<span id="cb431-63"><a href="#cb431-63" aria-hidden="true" tabindex="-1"></a><span class="co"># happy_not_dem</span></span>
<span id="cb431-64"><a href="#cb431-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-65"><a href="#cb431-65" aria-hidden="true" tabindex="-1"></a><span class="co"># after looking through it, it seems that the countries that were in dem_not_happy were a lot of small, island based nation states that don't necessarily need to be included for this to be a fair comparison. The countries in happy_not_dem were all countries with names that may be different between the two sets. these are the countries we will recode. Using my own imperfect analysis, I have chosen the countries I will use from this list of unmatched country names, and I will use this to find the names for those countries in the democracy df</span></span>
<span id="cb431-66"><a href="#cb431-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-67"><a href="#cb431-67" aria-hidden="true" tabindex="-1"></a>avg_dem <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">str_detect</span>(country_name, <span class="st">"Korea|Mold|Congo|Trinidad|Hong|Palest|Taiwan|Turkey|Czech|Gambia|Slov"</span>))</span>
<span id="cb431-68"><a href="#cb431-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-69"><a href="#cb431-69" aria-hidden="true" tabindex="-1"></a><span class="co"># now that we know the names of all the countries that we want in both data sets, I will fix the happiness dataset to match the names from the democracy set, and then we will use an inner join to only get the countries that we want.</span></span>
<span id="cb431-70"><a href="#cb431-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-71"><a href="#cb431-71" aria-hidden="true" tabindex="-1"></a>country_fix_happiness <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb431-72"><a href="#cb431-72" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Congo"</span> <span class="ot">=</span> <span class="st">"Congo, Republic of"</span>,</span>
<span id="cb431-73"><a href="#cb431-73" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Czechia"</span> <span class="ot">=</span> <span class="st">"Czech Republic"</span>,</span>
<span id="cb431-74"><a href="#cb431-74" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Côte d’Ivoire"</span> <span class="ot">=</span> <span class="st">"Ivory Coast"</span>,</span>
<span id="cb431-75"><a href="#cb431-75" aria-hidden="true" tabindex="-1"></a>  <span class="st">"DR Congo"</span> <span class="ot">=</span> <span class="st">"Congo, Dem. Rep."</span>,</span>
<span id="cb431-76"><a href="#cb431-76" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Gambia"</span> <span class="ot">=</span> <span class="st">"Gambia, The"</span>,</span>
<span id="cb431-77"><a href="#cb431-77" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Hong Kong SAR of China"</span> <span class="ot">=</span> <span class="st">"Hong Kong"</span>,</span>
<span id="cb431-78"><a href="#cb431-78" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Lao PDR"</span> <span class="ot">=</span> <span class="st">"Laos"</span>,</span>
<span id="cb431-79"><a href="#cb431-79" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Republic of Korea"</span> <span class="ot">=</span> <span class="st">"Korea, Republic of"</span>,</span>
<span id="cb431-80"><a href="#cb431-80" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Republic of Moldova"</span> <span class="ot">=</span> <span class="st">"Moldova"</span>,</span>
<span id="cb431-81"><a href="#cb431-81" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Russian Federation"</span> <span class="ot">=</span> <span class="st">"Russia"</span>,</span>
<span id="cb431-82"><a href="#cb431-82" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Slovakia"</span> <span class="ot">=</span> <span class="st">"Slovak Republic"</span>,</span>
<span id="cb431-83"><a href="#cb431-83" aria-hidden="true" tabindex="-1"></a>  <span class="st">"State of Palestine"</span> <span class="ot">=</span> <span class="st">"Palestine"</span>,</span>
<span id="cb431-84"><a href="#cb431-84" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Taiwan Province of China"</span> <span class="ot">=</span> <span class="st">"Taiwan"</span>,</span>
<span id="cb431-85"><a href="#cb431-85" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Trinidad and Tobago"</span> <span class="ot">=</span> <span class="st">"Trinidad &amp;Tobago"</span>,</span>
<span id="cb431-86"><a href="#cb431-86" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Türkiye"</span> <span class="ot">=</span> <span class="st">"Turkey"</span>,</span>
<span id="cb431-87"><a href="#cb431-87" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Viet Nam"</span> <span class="ot">=</span> <span class="st">"Vietnam"</span>)</span>
<span id="cb431-88"><a href="#cb431-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-89"><a href="#cb431-89" aria-hidden="true" tabindex="-1"></a>avg_happiness_fixed <span class="ot">&lt;-</span> happiness_overlap <span class="sc">%&gt;%</span></span>
<span id="cb431-90"><a href="#cb431-90" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">country_name =</span> <span class="fu">recode</span>(country_name, <span class="sc">!!!</span>country_fix_happiness)) <span class="sc">%&gt;%</span></span>
<span id="cb431-91"><a href="#cb431-91" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country_name) <span class="sc">%&gt;%</span></span>
<span id="cb431-92"><a href="#cb431-92" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_well_being =</span> <span class="fu">mean</span>(well_being, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb431-93"><a href="#cb431-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-94"><a href="#cb431-94" aria-hidden="true" tabindex="-1"></a>hdiXdem_df <span class="ot">&lt;-</span> avg_dem <span class="sc">%&gt;%</span></span>
<span id="cb431-95"><a href="#cb431-95" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(avg_happiness_fixed, <span class="at">by =</span> <span class="st">"country_name"</span>)</span>
<span id="cb431-96"><a href="#cb431-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-97"><a href="#cb431-97" aria-hidden="true" tabindex="-1"></a><span class="co"># head(hdiXdem_df)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Geopolitical structures are very diverse, with everything from parliamentary democracies to theocratic authoritarian regimes. In the United States, the concepts of democracy and representation have basically become normative and almost inherently ethical, so much so that this reasoning has been the basis for heavy involvement and regime change across the world. With this, it is important to take a step back and wonder, does this even matter? Is the democratic structure the most conducive for well-being? Are our structures of representation meaningful when it comes to our qualities of democracy? As norms get disrupted, and streaks of populism keep growing, it is crucial to analyze if our established structures really do bolster well-being for its constituents.</p>
</section>
<section id="does-a-countrys-representation-even-relate-to-their-democracy-quality" class="level2">
<h2 class="anchored" data-anchor-id="does-a-countrys-representation-even-relate-to-their-democracy-quality">Does a country’s representation even relate to their democracy quality?</h2>
<p>We first use a dataset made avaiable through TidyTuesdayR. It contains information from 1955 to 2020 about the geopolitical structure of every country in the world. Example variables include democracy status, a regime category index, and communist status. The collection of this data has largely been ongoing, but I believe was compiled fairly recently. This kind of data is usually easily attainable because most variables are yes/no questions such as, “Was this country a democracy?”. Each observational unit is a combination of country and year, so e.g.&nbsp;Albania 1962. This is a very interesting dataset because with the presence of variables such as that give scores to a country’s democracy, hold the number of representatives, and even test if they have free and fair elections, you can make some really interesting conclusions about what we consider as some of the most sacred aspects of a society. For example, an idea that we have is testing a relationship with spatial democracy index vs.&nbsp;total representation to test the long held and intuitive belief that more representation per person leads to better democracies. To obtain this population data, we used an API to collect historical population data. This data was collected every five years since 1955, and is widely accessible through public historical population records. This data was of interest to us because making conclusions about the efficacy of representation is not really useful without some adjusting for population. For example, a country like china may have a lot of representatives but this could be disanalogous with their democracy quality because of the fact that China is the most populated country in the world.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb432"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb432-1"><a href="#cb432-1" aria-hidden="true" tabindex="-1"></a>democracy_data <span class="ot">&lt;-</span> tuesdata<span class="sc">$</span>democracy_data</span>
<span id="cb432-2"><a href="#cb432-2" aria-hidden="true" tabindex="-1"></a>countries <span class="ot">&lt;-</span> <span class="fu">unique</span>(democracy_data<span class="sc">$</span>country_name)</span>
<span id="cb432-3"><a href="#cb432-3" aria-hidden="true" tabindex="-1"></a>total_reps <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(countries))</span>
<span id="cb432-4"><a href="#cb432-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb432-5"><a href="#cb432-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(countries)) {</span>
<span id="cb432-6"><a href="#cb432-6" aria-hidden="true" tabindex="-1"></a>  this_country <span class="ot">&lt;-</span> countries[i]</span>
<span id="cb432-7"><a href="#cb432-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb432-8"><a href="#cb432-8" aria-hidden="true" tabindex="-1"></a>  total_reps[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(</span>
<span id="cb432-9"><a href="#cb432-9" aria-hidden="true" tabindex="-1"></a>    democracy_data<span class="sc">$</span>lower_house_members[democracy_data<span class="sc">$</span>country_name <span class="sc">==</span> this_country],</span>
<span id="cb432-10"><a href="#cb432-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span>)}</span>
<span id="cb432-11"><a href="#cb432-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb432-12"><a href="#cb432-12" aria-hidden="true" tabindex="-1"></a>country_rep_summary <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb432-13"><a href="#cb432-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">country_name =</span> countries,</span>
<span id="cb432-14"><a href="#cb432-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_lower_house_members =</span> total_reps)</span>
<span id="cb432-15"><a href="#cb432-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb432-16"><a href="#cb432-16" aria-hidden="true" tabindex="-1"></a>country_rep_summary <span class="ot">&lt;-</span> country_rep_summary[<span class="fu">order</span>(<span class="sc">-</span>country_rep_summary<span class="sc">$</span>total_lower_house_members), ]</span>
<span id="cb432-17"><a href="#cb432-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb432-18"><a href="#cb432-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb432-19"><a href="#cb432-19" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb432-20"><a href="#cb432-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(country_rep_summary, <span class="dv">20</span>),</span>
<span id="cb432-21"><a href="#cb432-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Country"</span>, <span class="st">"Total Lower House Members"</span>),</span>
<span id="cb432-22"><a href="#cb432-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Total lower house members by country"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Total lower house members by country</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Country</th>
<th style="text-align: right;">Total Lower House Members</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">40</td>
<td style="text-align: left;">China</td>
<td style="text-align: right;">122260</td>
</tr>
<tr class="even">
<td style="text-align: left;">107</td>
<td style="text-align: left;">Libya</td>
<td style="text-align: right;">94678</td>
</tr>
<tr class="odd">
<td style="text-align: left;">154</td>
<td style="text-align: left;">Russia</td>
<td style="text-align: right;">49915</td>
</tr>
<tr class="even">
<td style="text-align: left;">192</td>
<td style="text-align: left;">Turkmenistan</td>
<td style="text-align: right;">46626</td>
</tr>
<tr class="odd">
<td style="text-align: left;">198</td>
<td style="text-align: left;">United Kingdom</td>
<td style="text-align: right;">45567</td>
</tr>
<tr class="even">
<td style="text-align: left;">91</td>
<td style="text-align: left;">Italy</td>
<td style="text-align: right;">44192</td>
</tr>
<tr class="odd">
<td style="text-align: left;">70</td>
<td style="text-align: left;">Germany</td>
<td style="text-align: right;">39582</td>
</tr>
<tr class="even">
<td style="text-align: left;">66</td>
<td style="text-align: left;">France</td>
<td style="text-align: right;">39273</td>
</tr>
<tr class="odd">
<td style="text-align: left;">98</td>
<td style="text-align: left;">Korea, People’s Republic</td>
<td style="text-align: right;">38419</td>
</tr>
<tr class="even">
<td style="text-align: left;">85</td>
<td style="text-align: left;">India</td>
<td style="text-align: right;">37213</td>
</tr>
<tr class="odd">
<td style="text-align: left;">93</td>
<td style="text-align: left;">Japan</td>
<td style="text-align: right;">34591</td>
</tr>
<tr class="even">
<td style="text-align: left;">191</td>
<td style="text-align: left;">Turkey</td>
<td style="text-align: right;">34052</td>
</tr>
<tr class="odd">
<td style="text-align: left;">149</td>
<td style="text-align: left;">Poland</td>
<td style="text-align: right;">32468</td>
</tr>
<tr class="even">
<td style="text-align: left;">205</td>
<td style="text-align: left;">Vietnam</td>
<td style="text-align: right;">31019</td>
</tr>
<tr class="odd">
<td style="text-align: left;">26</td>
<td style="text-align: left;">Brazil</td>
<td style="text-align: right;">30918</td>
</tr>
<tr class="even">
<td style="text-align: left;">199</td>
<td style="text-align: left;">United States</td>
<td style="text-align: right;">30893</td>
</tr>
<tr class="odd">
<td style="text-align: left;">86</td>
<td style="text-align: left;">Indonesia</td>
<td style="text-align: right;">29684</td>
</tr>
<tr class="even">
<td style="text-align: left;">153</td>
<td style="text-align: left;">Romania</td>
<td style="text-align: right;">27768</td>
</tr>
<tr class="odd">
<td style="text-align: left;">49</td>
<td style="text-align: left;">Cuba</td>
<td style="text-align: right;">25949</td>
</tr>
<tr class="even">
<td style="text-align: left;">121</td>
<td style="text-align: left;">Mexico</td>
<td style="text-align: right;">24739</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This table highlights countries with the largest total number of lower house representatives. Larger and more populous countries tend to dominate this list, reflecting the scale of their political systems. As we prepare to analyze the representation score per country, we need to gather total numbers of representatives across chambers. This can present itself as a challenge because we have encountered the fact that countries have different ways of organizing their representatives. For example, while the United States has a bicameral legislature, there is an additional column in the dataset for a third house, which we had to account for. Overall, this table both helps us get a good idea for the front runners of representation, and at the same time helps us prepare to gather population data to take some averages to get a population adjusted representation measure.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb433"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb433-1"><a href="#cb433-1" aria-hidden="true" tabindex="-1"></a>dem_index<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/egregi0us/political-system-analysis/refs/heads/main/democracy-index-eiu.csv"</span>)</span>
<span id="cb433-2"><a href="#cb433-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb433-3"><a href="#cb433-3" aria-hidden="true" tabindex="-1"></a>dem_index2<span class="ot">&lt;-</span>dem_index <span class="sc">%&gt;%</span></span>
<span id="cb433-4"><a href="#cb433-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">country =</span> <span class="st">"Entity"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb433-5"><a href="#cb433-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">year=</span><span class="st">"Year"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb433-6"><a href="#cb433-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">&gt;</span><span class="dv">2006</span> <span class="sc">&amp;</span> year<span class="sc">%%</span><span class="dv">5</span><span class="sc">==</span><span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb434"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb434-1"><a href="#cb434-1" aria-hidden="true" tabindex="-1"></a>finalest_df <span class="ot">&lt;-</span> final_df <span class="sc">%&gt;%</span></span>
<span id="cb434-2"><a href="#cb434-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>pop_prop <span class="sc">==</span> <span class="cn">Inf</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb435"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb435-1"><a href="#cb435-1" aria-hidden="true" tabindex="-1"></a>finalestest_df <span class="ot">&lt;-</span> <span class="fu">left_join</span>(finalest_df, dem_index2, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"country"</span>,<span class="st">"year"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb436"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb436-1"><a href="#cb436-1" aria-hidden="true" tabindex="-1"></a>finalestest_df<span class="ot">&lt;-</span> finalestest_df <span class="sc">%&gt;%</span></span>
<span id="cb436-2"><a href="#cb436-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">&gt;</span><span class="dv">2005</span>)<span class="sc">%&gt;%</span></span>
<span id="cb436-3"><a href="#cb436-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Democracy.Index))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb437"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb437-1"><a href="#cb437-1" aria-hidden="true" tabindex="-1"></a>finalestest_df <span class="sc">%&gt;%</span></span>
<span id="cb437-2"><a href="#cb437-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(country, year, spatial_democracy, Democracy.Index, population, pop_prop) <span class="sc">%&gt;%</span></span>
<span id="cb437-3"><a href="#cb437-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> Democracy.Index, <span class="at">n=</span><span class="dv">15</span>) <span class="sc">%&gt;%</span></span>
<span id="cb437-4"><a href="#cb437-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb437-5"><a href="#cb437-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">spatial_democracy =</span> <span class="fu">round</span>(spatial_democracy, <span class="dv">3</span>),</span>
<span id="cb437-6"><a href="#cb437-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Democracy.Index =</span> <span class="fu">round</span>(Democracy.Index, <span class="dv">3</span>),</span>
<span id="cb437-7"><a href="#cb437-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">population =</span> scales<span class="sc">::</span><span class="fu">comma</span>(population),</span>
<span id="cb437-8"><a href="#cb437-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">pop_prop =</span> scales<span class="sc">::</span><span class="fu">comma</span>(<span class="fu">round</span>(pop_prop, <span class="dv">0</span>))</span>
<span id="cb437-9"><a href="#cb437-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb437-10"><a href="#cb437-10" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb437-11"><a href="#cb437-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(</span>
<span id="cb437-12"><a href="#cb437-12" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Country"</span>,</span>
<span id="cb437-13"><a href="#cb437-13" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Year"</span>,</span>
<span id="cb437-14"><a href="#cb437-14" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Spatial Democracy"</span>,</span>
<span id="cb437-15"><a href="#cb437-15" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Democracy Index"</span>,</span>
<span id="cb437-16"><a href="#cb437-16" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Population"</span>,</span>
<span id="cb437-17"><a href="#cb437-17" aria-hidden="true" tabindex="-1"></a>      <span class="st">"People per Representative"</span></span>
<span id="cb437-18"><a href="#cb437-18" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb437-19"><a href="#cb437-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Democracy, population, and representation summary for selected countries."</span>,</span>
<span id="cb437-20"><a href="#cb437-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"c"</span></span>
<span id="cb437-21"><a href="#cb437-21" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Democracy, population, and representation summary for selected countries.</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 20%">
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Country</th>
<th style="text-align: center;">Year</th>
<th style="text-align: center;">Spatial Democracy</th>
<th style="text-align: center;">Democracy Index</th>
<th style="text-align: center;">Population</th>
<th style="text-align: center;">People per Representative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Norway</td>
<td style="text-align: center;">2015</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.93</td>
<td style="text-align: center;">5,189,771</td>
<td style="text-align: center;">30,709</td>
</tr>
<tr class="even">
<td style="text-align: center;">Norway</td>
<td style="text-align: center;">2020</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.81</td>
<td style="text-align: center;">5,379,274</td>
<td style="text-align: center;">31,830</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Norway</td>
<td style="text-align: center;">2010</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.80</td>
<td style="text-align: center;">4,889,162</td>
<td style="text-align: center;">28,930</td>
</tr>
<tr class="even">
<td style="text-align: center;">Iceland</td>
<td style="text-align: center;">2010</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.65</td>
<td style="text-align: center;">318,158</td>
<td style="text-align: center;">5,050</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Iceland</td>
<td style="text-align: center;">2015</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.58</td>
<td style="text-align: center;">330,952</td>
<td style="text-align: center;">5,253</td>
</tr>
<tr class="even">
<td style="text-align: center;">Denmark</td>
<td style="text-align: center;">2010</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.52</td>
<td style="text-align: center;">5,547,863</td>
<td style="text-align: center;">30,994</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sweden</td>
<td style="text-align: center;">2010</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.50</td>
<td style="text-align: center;">9,378,232</td>
<td style="text-align: center;">26,872</td>
</tr>
<tr class="even">
<td style="text-align: center;">Sweden</td>
<td style="text-align: center;">2015</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.45</td>
<td style="text-align: center;">9,799,481</td>
<td style="text-align: center;">28,079</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Iceland</td>
<td style="text-align: center;">2020</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.37</td>
<td style="text-align: center;">366,614</td>
<td style="text-align: center;">5,819</td>
</tr>
<tr class="even">
<td style="text-align: center;">New Zealand</td>
<td style="text-align: center;">2010</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.26</td>
<td style="text-align: center;">4,347,770</td>
<td style="text-align: center;">36,231</td>
</tr>
<tr class="odd">
<td style="text-align: center;">New Zealand</td>
<td style="text-align: center;">2015</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.26</td>
<td style="text-align: center;">4,614,029</td>
<td style="text-align: center;">38,450</td>
</tr>
<tr class="even">
<td style="text-align: center;">Sweden</td>
<td style="text-align: center;">2020</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.26</td>
<td style="text-align: center;">10,353,686</td>
<td style="text-align: center;">29,667</td>
</tr>
<tr class="odd">
<td style="text-align: center;">New Zealand</td>
<td style="text-align: center;">2020</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.25</td>
<td style="text-align: center;">5,069,895</td>
<td style="text-align: center;">42,249</td>
</tr>
<tr class="even">
<td style="text-align: center;">Canada</td>
<td style="text-align: center;">2020</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.24</td>
<td style="text-align: center;">38,171,902</td>
<td style="text-align: center;">92,426</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Australia</td>
<td style="text-align: center;">2010</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9.22</td>
<td style="text-align: center;">22,141,581</td>
<td style="text-align: center;">97,972</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This table shows how population, representation, and democracy scores vary across countries and years. All of these variables are extraordinarily useful for our questions, as it provides context for understanding how representation per person may relate to democratic outcomes. It includes two measures of democracy, both spatial democracy score and democracy index. These were pulled from different sources, and really only differ by the fact that the democracy index seems to be less clustered around certain values between 0 and 1.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb438"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb438-1"><a href="#cb438-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(countrycode)</span>
<span id="cb438-2"><a href="#cb438-2" aria-hidden="true" tabindex="-1"></a>vis2 <span class="ot">&lt;-</span> final_df <span class="sc">|&gt;</span></span>
<span id="cb438-3"><a href="#cb438-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(country, spatial_democracy, pop_prop) <span class="sc">|&gt;</span></span>
<span id="cb438-4"><a href="#cb438-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">region =</span> <span class="fu">countrycode</span>(country,</span>
<span id="cb438-5"><a href="#cb438-5" aria-hidden="true" tabindex="-1"></a>                              <span class="at">origin =</span> <span class="st">"country.name"</span>,</span>
<span id="cb438-6"><a href="#cb438-6" aria-hidden="true" tabindex="-1"></a>                              <span class="at">destination =</span> <span class="st">"continent"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb438-7"><a href="#cb438-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>pop_prop<span class="sc">==</span><span class="cn">Inf</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb439"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb439-1"><a href="#cb439-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cowplot)</span>
<span id="cb439-2"><a href="#cb439-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggridges)</span>
<span id="cb439-3"><a href="#cb439-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb440"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb440-1"><a href="#cb440-1" aria-hidden="true" tabindex="-1"></a>title_theme <span class="ot">&lt;-</span> <span class="fu">ggdraw</span>() <span class="sc">+</span></span>
<span id="cb440-2"><a href="#cb440-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">draw_label</span>(<span class="st">"Spatial Democracy Versus Person per Representative by Region"</span>,</span>
<span id="cb440-3"><a href="#cb440-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">fontfamily =</span> <span class="st">"Courier"</span>,</span>
<span id="cb440-4"><a href="#cb440-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fontface =</span> <span class="st">"bold"</span>,</span>
<span id="cb440-5"><a href="#cb440-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">9</span>,</span>
<span id="cb440-6"><a href="#cb440-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">hjust =</span> <span class="fl">0.42</span></span>
<span id="cb440-7"><a href="#cb440-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb440-8"><a href="#cb440-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb440-9"><a href="#cb440-9" aria-hidden="true" tabindex="-1"></a>spa_dem <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(vis2, <span class="fu">aes</span>(<span class="at">x =</span> spatial_democracy,</span>
<span id="cb440-10"><a href="#cb440-10" aria-hidden="true" tabindex="-1"></a>                            <span class="at">y =</span> <span class="fu">reorder</span>(region, spatial_democracy),</span>
<span id="cb440-11"><a href="#cb440-11" aria-hidden="true" tabindex="-1"></a>                            <span class="at">fill =</span> region)) <span class="sc">+</span></span>
<span id="cb440-12"><a href="#cb440-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density_ridges</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">scale =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb440-13"><a href="#cb440-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb440-14"><a href="#cb440-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Spatial Democracy Index"</span>,</span>
<span id="cb440-15"><a href="#cb440-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">" "</span>) <span class="sc">+</span></span>
<span id="cb440-16"><a href="#cb440-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Dark2"</span>) <span class="sc">+</span></span>
<span id="cb440-17"><a href="#cb440-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>)</span>
<span id="cb440-18"><a href="#cb440-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb440-19"><a href="#cb440-19" aria-hidden="true" tabindex="-1"></a>pop_dem <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(vis2, <span class="fu">aes</span>(<span class="at">x =</span> pop_prop,</span>
<span id="cb440-20"><a href="#cb440-20" aria-hidden="true" tabindex="-1"></a>                            <span class="at">y =</span> <span class="fu">reorder</span>(region, pop_prop),</span>
<span id="cb440-21"><a href="#cb440-21" aria-hidden="true" tabindex="-1"></a>                            <span class="at">fill =</span> region)) <span class="sc">+</span></span>
<span id="cb440-22"><a href="#cb440-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density_ridges</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">scale =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb440-23"><a href="#cb440-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">50000</span>), <span class="at">labels =</span> <span class="fu">label_number</span>(<span class="at">scale_cut =</span> <span class="fu">cut_short_scale</span>())) <span class="sc">+</span></span>
<span id="cb440-24"><a href="#cb440-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Person per Rep"</span>,</span>
<span id="cb440-25"><a href="#cb440-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">" "</span>) <span class="sc">+</span></span>
<span id="cb440-26"><a href="#cb440-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Dark2"</span>) <span class="sc">+</span></span>
<span id="cb440-27"><a href="#cb440-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>)</span>
<span id="cb440-28"><a href="#cb440-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb440-29"><a href="#cb440-29" aria-hidden="true" tabindex="-1"></a>gridofplots <span class="ot">&lt;-</span> <span class="fu">plot_grid</span>(spa_dem, pop_dem, <span class="at">nrow =</span> <span class="dv">1</span>)</span>
<span id="cb440-30"><a href="#cb440-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb440-31"><a href="#cb440-31" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_grid</span>(title_theme,</span>
<span id="cb440-32"><a href="#cb440-32" aria-hidden="true" tabindex="-1"></a>  gridofplots,</span>
<span id="cb440-33"><a href="#cb440-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">rel_heights =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">1.5</span>, <span class="fl">0.1</span>)</span>
<span id="cb440-34"><a href="#cb440-34" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="representation_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>These plots show how both democracy scores and representation levels vary across regions. This is useful to us because we can see how spatial democracy and representation are distributed by continent. This can help us spot out meaningful differences not just between countries in the data summaries before, but also by continent. Continental patterns can lead to more questions such as what factors that are present continent wide can lead to such disparities? A famous example of these sorts of questions are present in “Guns, Germs, and Steel” by Jared Diamond, where he attributes the disparities between Africa and parts of Asia to the presence of certain crops and livestock, as well as geographical differences.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb441"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb441-1"><a href="#cb441-1" aria-hidden="true" tabindex="-1"></a>final_df <span class="sc">%&gt;%</span></span>
<span id="cb441-2"><a href="#cb441-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>pop_prop, <span class="at">y =</span> spatial_democracy))<span class="sc">+</span></span>
<span id="cb441-3"><a href="#cb441-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>)<span class="sc">+</span></span>
<span id="cb441-4"><a href="#cb441-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb441-5"><a href="#cb441-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Population Proportion"</span>,</span>
<span id="cb441-6"><a href="#cb441-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Spatial Democracy"</span>,</span>
<span id="cb441-7"><a href="#cb441-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Jitter Plot, Population Proportion v. Spatial Democracy"</span></span>
<span id="cb441-8"><a href="#cb441-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="representation_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This scatterplot shows a wide spread in democracy scores across different levels of population per representative. While there is some visible pattern, the relationship appears noisy and not strictly linear. This is largely due to a shortcoming in our data, being that spatial democracy is a categorical-like quantitative variable, meaning that even though its measured in numbers, its largely easy numbers to work with between 0 and 1, so 0.5,0.6,0.25 for example. This leads to clustering as you can see in the scatterplot. However, past this we can still see some negative trend in the data, indicating a potential negative relationship between spatial democracy and population adjusted representation. Note that the way that we measured representation leads to a higher number meaning lower representation since our population adjusting was measured in person per representative.</p>
</section>
<section id="does-the-quality-of-a-countrys-democracy-even-relate-to-their-overall-happiness" class="level2">
<h2 class="anchored" data-anchor-id="does-the-quality-of-a-countrys-democracy-even-relate-to-their-overall-happiness">Does the quality of a country’s democracy even relate to their overall happiness?</h2>
<p>The data pertaining to this research question was read in through a csv file accessed through the World Bank website. It contains the Human Development Indexes of every country. HDI is a rough measurement of the quality of life in countries, broken down into three main measurements; years of education, life expectancy, and gross national income. This was of great use because we wanted to see the connection between the spatial democracy index and happiness index of a country. We wanted to do this because this could help us with a greater connection between greater representation and the happiness/well-being of a country.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb442"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb442-1"><a href="#cb442-1" aria-hidden="true" tabindex="-1"></a>final_df <span class="ot">&lt;-</span> final_df <span class="sc">%&gt;%</span></span>
<span id="cb442-2"><a href="#cb442-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(is_democracy<span class="sc">==</span><span class="cn">TRUE</span>)<span class="sc">%&gt;%</span></span>
<span id="cb442-3"><a href="#cb442-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>pop_prop<span class="sc">==</span><span class="cn">Inf</span>)<span class="sc">%&gt;%</span></span>
<span id="cb442-4"><a href="#cb442-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pop_prop =</span> population<span class="sc">/</span><span class="fu">rowSums</span>(<span class="fu">cbind</span>(upper_house_members,lower_house_members, third_house_members), <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb443"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb443-1"><a href="#cb443-1" aria-hidden="true" tabindex="-1"></a>final_df <span class="sc">%&gt;%</span></span>
<span id="cb443-2"><a href="#cb443-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(country, year, population, pop_prop) <span class="sc">%&gt;%</span></span>
<span id="cb443-3"><a href="#cb443-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> pop_prop, <span class="at">n=</span><span class="dv">15</span>) <span class="sc">%&gt;%</span></span>
<span id="cb443-4"><a href="#cb443-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb443-5"><a href="#cb443-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">population =</span> scales<span class="sc">::</span><span class="fu">comma</span>(population),</span>
<span id="cb443-6"><a href="#cb443-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pop_prop =</span> scales<span class="sc">::</span><span class="fu">comma</span>(<span class="fu">round</span>(pop_prop, <span class="dv">0</span>))</span>
<span id="cb443-7"><a href="#cb443-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb443-8"><a href="#cb443-8" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb443-9"><a href="#cb443-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(</span>
<span id="cb443-10"><a href="#cb443-10" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Country"</span>,</span>
<span id="cb443-11"><a href="#cb443-11" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Year"</span>,</span>
<span id="cb443-12"><a href="#cb443-12" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Population"</span>,</span>
<span id="cb443-13"><a href="#cb443-13" aria-hidden="true" tabindex="-1"></a>      <span class="st">"People per Representative"</span></span>
<span id="cb443-14"><a href="#cb443-14" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb443-15"><a href="#cb443-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Population-adjusted representation for selected democratic countries."</span>,</span>
<span id="cb443-16"><a href="#cb443-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"c"</span></span>
<span id="cb443-17"><a href="#cb443-17" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Population-adjusted representation for selected democratic countries.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Country</th>
<th style="text-align: center;">Year</th>
<th style="text-align: center;">Population</th>
<th style="text-align: center;">People per Representative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">India</td>
<td style="text-align: center;">2020</td>
<td style="text-align: center;">1,402,617,695</td>
<td style="text-align: center;">1,779,972</td>
</tr>
<tr class="even">
<td style="text-align: center;">India</td>
<td style="text-align: center;">2015</td>
<td style="text-align: center;">1,328,024,498</td>
<td style="text-align: center;">1,685,310</td>
</tr>
<tr class="odd">
<td style="text-align: center;">India</td>
<td style="text-align: center;">2010</td>
<td style="text-align: center;">1,243,481,564</td>
<td style="text-align: center;">1,578,022</td>
</tr>
<tr class="even">
<td style="text-align: center;">India</td>
<td style="text-align: center;">2005</td>
<td style="text-align: center;">1,154,676,322</td>
<td style="text-align: center;">1,465,325</td>
</tr>
<tr class="odd">
<td style="text-align: center;">India</td>
<td style="text-align: center;">2000</td>
<td style="text-align: center;">1,057,922,733</td>
<td style="text-align: center;">1,339,143</td>
</tr>
<tr class="even">
<td style="text-align: center;">India</td>
<td style="text-align: center;">1995</td>
<td style="text-align: center;">960,301,044</td>
<td style="text-align: center;">1,215,571</td>
</tr>
<tr class="odd">
<td style="text-align: center;">India</td>
<td style="text-align: center;">1990</td>
<td style="text-align: center;">864,972,221</td>
<td style="text-align: center;">1,094,902</td>
</tr>
<tr class="even">
<td style="text-align: center;">India</td>
<td style="text-align: center;">1985</td>
<td style="text-align: center;">772,647,793</td>
<td style="text-align: center;">994,399</td>
</tr>
<tr class="odd">
<td style="text-align: center;">India</td>
<td style="text-align: center;">1980</td>
<td style="text-align: center;">687,354,025</td>
<td style="text-align: center;">874,496</td>
</tr>
<tr class="even">
<td style="text-align: center;">Curacao</td>
<td style="text-align: center;">2020</td>
<td style="text-align: center;">17,636,731</td>
<td style="text-align: center;">839,844</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Curacao</td>
<td style="text-align: center;">2015</td>
<td style="text-align: center;">17,107,433</td>
<td style="text-align: center;">814,640</td>
</tr>
<tr class="even">
<td style="text-align: center;">India</td>
<td style="text-align: center;">1975</td>
<td style="text-align: center;">611,309,535</td>
<td style="text-align: center;">802,243</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Curacao</td>
<td style="text-align: center;">2010</td>
<td style="text-align: center;">16,771,235</td>
<td style="text-align: center;">762,329</td>
</tr>
<tr class="even">
<td style="text-align: center;">Curacao</td>
<td style="text-align: center;">2005</td>
<td style="text-align: center;">16,465,710</td>
<td style="text-align: center;">748,441</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Curacao</td>
<td style="text-align: center;">2000</td>
<td style="text-align: center;">16,058,760</td>
<td style="text-align: center;">729,944</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This table illustrates how population and representation levels change over time for different countries. This can highlight changes in historical and geopolitical trends, such as the rise of democratic nations over the past seventy years, and the challenges of some countries with overcoming monarchic structures. Since we are measuring in people per representative, this selection shows the least representative countries adjusted per population. Overall, we can see evolution of a country’s structure by the progression of their representation numbers every five years.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb444"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb444-1"><a href="#cb444-1" aria-hidden="true" tabindex="-1"></a>avg_dem <span class="ot">&lt;-</span> <span class="cf">function</span>(country) {</span>
<span id="cb444-2"><a href="#cb444-2" aria-hidden="true" tabindex="-1"></a>  dem_df <span class="sc">%&gt;%</span></span>
<span id="cb444-3"><a href="#cb444-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(country_name <span class="sc">==</span> country) <span class="sc">%&gt;%</span></span>
<span id="cb444-4"><a href="#cb444-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">avg =</span> <span class="fu">mean</span>(spatial_democracy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb444-5"><a href="#cb444-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(avg)</span>
<span id="cb444-6"><a href="#cb444-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb444-7"><a href="#cb444-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb444-8"><a href="#cb444-8" aria-hidden="true" tabindex="-1"></a>avg_df <span class="ot">&lt;-</span> dem_df <span class="sc">%&gt;%</span></span>
<span id="cb444-9"><a href="#cb444-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(country_name) <span class="sc">%&gt;%</span></span>
<span id="cb444-10"><a href="#cb444-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Average_Democracy =</span> <span class="fu">map_dbl</span>(country_name, avg_dem))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb445"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb445-1"><a href="#cb445-1" aria-hidden="true" tabindex="-1"></a>avg_df <span class="sc">%&gt;%</span></span>
<span id="cb445-2"><a href="#cb445-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb445-3"><a href="#cb445-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Average_Democracy =</span> <span class="fu">round</span>(Average_Democracy, <span class="dv">3</span>)</span>
<span id="cb445-4"><a href="#cb445-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb445-5"><a href="#cb445-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> Average_Democracy, <span class="at">n=</span><span class="dv">15</span>)<span class="sc">%&gt;%</span></span>
<span id="cb445-6"><a href="#cb445-6" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb445-7"><a href="#cb445-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(</span>
<span id="cb445-8"><a href="#cb445-8" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Country"</span>,</span>
<span id="cb445-9"><a href="#cb445-9" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Average Democracy Score"</span></span>
<span id="cb445-10"><a href="#cb445-10" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb445-11"><a href="#cb445-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Average spatial democracy score by country."</span>,</span>
<span id="cb445-12"><a href="#cb445-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"c"</span></span>
<span id="cb445-13"><a href="#cb445-13" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Average spatial democracy score by country.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Country</th>
<th style="text-align: center;">Average Democracy Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Belgium</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Bermuda</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Canada</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Denmark</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Ireland</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Liechtenstein</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Luxembourg</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Monaco</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Netherlands</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">New Zealand</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Norway</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Sri Lanka</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sweden</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Switzerland</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">United Kingdom</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This table summarizes the average democracy score for each country. It provides a simplified measure of long-term democratic performance across nations. Looking at each spatial democracy score for 70 total years can be tough to digest, so getting an average look over the recorded history gives us a good preliminary look into the performance of a country. We do recognize however, that average does not provide a comprehensive look into the country’s quality of democracy. For example, countries like Japan, South Korea, and former USSR countries had quick turnaround to democratic structures.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb446"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb446-1"><a href="#cb446-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identifying which countries to label:</span></span>
<span id="cb446-2"><a href="#cb446-2" aria-hidden="true" tabindex="-1"></a>top_wb  <span class="ot">&lt;-</span> hdiXdem_df <span class="sc">%&gt;%</span> <span class="fu">slice_max</span>(avg_well_being, <span class="at">n =</span> <span class="dv">3</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>)</span>
<span id="cb446-3"><a href="#cb446-3" aria-hidden="true" tabindex="-1"></a>low_wb  <span class="ot">&lt;-</span> hdiXdem_df <span class="sc">%&gt;%</span> <span class="fu">slice_min</span>(avg_well_being, <span class="at">n =</span> <span class="dv">3</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>)</span>
<span id="cb446-4"><a href="#cb446-4" aria-hidden="true" tabindex="-1"></a>top_dem <span class="ot">&lt;-</span> hdiXdem_df <span class="sc">%&gt;%</span> <span class="fu">slice_max</span>(avg_democracy, <span class="at">n =</span> <span class="dv">2</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>)</span>
<span id="cb446-5"><a href="#cb446-5" aria-hidden="true" tabindex="-1"></a>low_dem <span class="ot">&lt;-</span> hdiXdem_df <span class="sc">%&gt;%</span> <span class="fu">slice_min</span>(avg_democracy, <span class="at">n =</span> <span class="dv">2</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>)</span>
<span id="cb446-6"><a href="#cb446-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb446-7"><a href="#cb446-7" aria-hidden="true" tabindex="-1"></a>label_countries <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(top_wb, low_wb, top_dem, low_dem) <span class="sc">%&gt;%</span></span>
<span id="cb446-8"><a href="#cb446-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(country_name, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb447"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb447-1"><a href="#cb447-1" aria-hidden="true" tabindex="-1"></a>scatter1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb447-2"><a href="#cb447-2" aria-hidden="true" tabindex="-1"></a>  hdiXdem_df,</span>
<span id="cb447-3"><a href="#cb447-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> avg_democracy, <span class="at">y =</span> avg_well_being)</span>
<span id="cb447-4"><a href="#cb447-4" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb447-5"><a href="#cb447-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">2.8</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb447-6"><a href="#cb447-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"orange"</span>) <span class="sc">+</span></span>
<span id="cb447-7"><a href="#cb447-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(</span>
<span id="cb447-8"><a href="#cb447-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> label_countries,</span>
<span id="cb447-9"><a href="#cb447-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> country_name),</span>
<span id="cb447-10"><a href="#cb447-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">3</span>,</span>
<span id="cb447-11"><a href="#cb447-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">max.overlaps =</span> <span class="dv">20</span></span>
<span id="cb447-12"><a href="#cb447-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb447-13"><a href="#cb447-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">number_format</span>(<span class="at">accuracy =</span> <span class="fl">0.1</span>)) <span class="sc">+</span></span>
<span id="cb447-14"><a href="#cb447-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">number_format</span>(<span class="at">accuracy =</span> <span class="fl">0.1</span>)) <span class="sc">+</span></span>
<span id="cb447-15"><a href="#cb447-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb447-16"><a href="#cb447-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Democracy and Well-Being Are Positively Associated"</span>,</span>
<span id="cb447-17"><a href="#cb447-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Country averages from 2011 to 2020"</span>,</span>
<span id="cb447-18"><a href="#cb447-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Average Spatial Democracy Score"</span>,</span>
<span id="cb447-19"><a href="#cb447-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Average Well-Being Score"</span></span>
<span id="cb447-20"><a href="#cb447-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb447-21"><a href="#cb447-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb447-22"><a href="#cb447-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb447-23"><a href="#cb447-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb447-24"><a href="#cb447-24" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb448"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb448-1"><a href="#cb448-1" aria-hidden="true" tabindex="-1"></a>scatter1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="representation_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" alt="Scatter plot of average spatial democracy scores versus average well-being for countries between 2011 and 2020. Each point represents a country. The points form an upward pattern, indicating that countries with higher democracy scores tend to have higher average well-being. A few countries at the high end are Finland, Switzerland, and Australia, and a few countries at the low end are Burundi, Central African Republic, and South Sudan." width="672"></p>
</figure>
</div>
</div>
</div>
<p>This scatter plot shows a clear positive relationship between democracy and well-being. Countries with higher democracy scores tend to have higher average well-being. This is a very important visualization because we can obtain a preliminary sense of an answer to our question, that yes, a good quality democracy does tend to bolster the happiness and well-being of its constituents. Therefore, if this does prove to be statistically true, then the next important task becomes finding ways to improve the quality of a democracy to foster well-being.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb449"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb449-1"><a href="#cb449-1" aria-hidden="true" tabindex="-1"></a>hdiXdem_df <span class="sc">%&gt;%</span></span>
<span id="cb449-2"><a href="#cb449-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb449-3"><a href="#cb449-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">democracy_group =</span> <span class="fu">case_when</span>(</span>
<span id="cb449-4"><a href="#cb449-4" aria-hidden="true" tabindex="-1"></a>      avg_democracy <span class="sc">&lt;</span> <span class="fl">0.33</span> <span class="sc">~</span> <span class="st">"Low"</span>,</span>
<span id="cb449-5"><a href="#cb449-5" aria-hidden="true" tabindex="-1"></a>      avg_democracy <span class="sc">&lt;</span> <span class="fl">0.66</span> <span class="sc">~</span> <span class="st">"Medium"</span>,</span>
<span id="cb449-6"><a href="#cb449-6" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"High"</span>),</span>
<span id="cb449-7"><a href="#cb449-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">democracy_group =</span> <span class="fu">factor</span>(democracy_group, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Medium"</span>, <span class="st">"High"</span>))</span>
<span id="cb449-8"><a href="#cb449-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb449-9"><a href="#cb449-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> democracy_group, <span class="at">y =</span> avg_well_being, <span class="at">fill =</span> democracy_group)) <span class="sc">+</span></span>
<span id="cb449-10"><a href="#cb449-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb449-11"><a href="#cb449-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb449-12"><a href="#cb449-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Well-Being Increases with Democracy Level"</span>,</span>
<span id="cb449-13"><a href="#cb449-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Democracy Level"</span>,</span>
<span id="cb449-14"><a href="#cb449-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Average Well-Being"</span></span>
<span id="cb449-15"><a href="#cb449-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb449-16"><a href="#cb449-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb449-17"><a href="#cb449-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb449-18"><a href="#cb449-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb449-19"><a href="#cb449-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span></span>
<span id="cb449-20"><a href="#cb449-20" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="representation_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Distribution of well-being across different levels of democracy.</figcaption>
</figure>
</div>
</div>
</div>
<p>This visualization shows that countries with higher levels of democracy generally have higher and more consistent well-being scores. The upward shift in medians reinforces the positive association. This is largely just a different angle of the same conclusion that a high quality democracy is associated with a higher average well-being. Again, this gives us further reason to conduct a statistical test to determine whether or not democracy level is truly associated with well being.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb450"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb450-1"><a href="#cb450-1" aria-hidden="true" tabindex="-1"></a>final_df <span class="ot">&lt;-</span> final_df <span class="sc">%&gt;%</span></span>
<span id="cb450-2"><a href="#cb450-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>pop_prop<span class="sc">==</span><span class="cn">Inf</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell" data-tbl-cap="Linear model predicting average well-being from average spatial democracy.">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb451"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb451-1"><a href="#cb451-1" aria-hidden="true" tabindex="-1"></a>rq2_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(avg_well_being <span class="sc">~</span> avg_democracy, <span class="at">data =</span> hdiXdem_df)</span>
<span id="cb451-2"><a href="#cb451-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb451-3"><a href="#cb451-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(rq2_model) <span class="sc">%&gt;%</span></span>
<span id="cb451-4"><a href="#cb451-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb451-5"><a href="#cb451-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">estimate =</span> <span class="fu">round</span>(estimate, <span class="dv">3</span>),</span>
<span id="cb451-6"><a href="#cb451-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">std.error =</span> <span class="fu">round</span>(std.error, <span class="dv">3</span>),</span>
<span id="cb451-7"><a href="#cb451-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="fu">round</span>(statistic, <span class="dv">3</span>),</span>
<span id="cb451-8"><a href="#cb451-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">p.value =</span> <span class="fu">pvalue</span>(p.value)</span>
<span id="cb451-9"><a href="#cb451-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb451-10"><a href="#cb451-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb451-11"><a href="#cb451-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Term =</span> term,</span>
<span id="cb451-12"><a href="#cb451-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Estimate =</span> estimate,</span>
<span id="cb451-13"><a href="#cb451-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Standard Error</span><span class="st">`</span> <span class="ot">=</span> std.error,</span>
<span id="cb451-14"><a href="#cb451-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">t-value</span><span class="st">`</span> <span class="ot">=</span> statistic,</span>
<span id="cb451-15"><a href="#cb451-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">p-value</span><span class="st">`</span> <span class="ot">=</span> p.value</span>
<span id="cb451-16"><a href="#cb451-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb451-17"><a href="#cb451-17" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb451-18"><a href="#cb451-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Linear regression model predicting average well-being from average spatial democracy."</span></span>
<span id="cb451-19"><a href="#cb451-19" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Linear model predicting average well-being from average spatial democracy.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Standard Error</th>
<th style="text-align: right;">t-value</th>
<th style="text-align: left;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">4.547</td>
<td style="text-align: right;">0.134</td>
<td style="text-align: right;">33.929</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg_democracy</td>
<td style="text-align: right;">1.557</td>
<td style="text-align: right;">0.203</td>
<td style="text-align: right;">7.678</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The linear regression results indicate a strong, statistically significant positive relationship between average spatial democracy and average well-being. The coefficient for average democracy is 1.557, meaning that for every one-unit increase in the democracy score (on a 0–1 scale), the model predicts an increase of approximately 1.56 points in a country’s average well-being score.</p>
<p>The p-value for this coefficient is &lt; 0.001, providing strong evidence that this relationship is statistically significant at the 0.05 level. This suggests that the observed positive association is very unlikely to be due to random chance.</p>
<p>The intercept of 4.547 represents the predicted well-being score when the democracy index is zero. This value is useful in practice, as some countries we are investigating have democracy indices of zero, so it serves as a baseline for the model.</p>
<p>Overall, these results support the conclusion that countries with higher levels of democracy tend to exhibit higher levels of well-being, reinforcing the idea that democratic structures may be associated with improved quality of life.</p>
<p>However, this model does not imply causation, and other factors such as economic development or regional differences may also influence well-being.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>